spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${spring.datasource.url}
    username: root
    password: ${spring.datasource.password}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
server:
  port: 8080